-- Target: ~/.config/hypr/autostart.lua
--
-- Nothing to autostart from here: mako, hypridle, hyprpaper, and hyprpolkitagent
-- each ship their own systemd --user service (WantedBy=graphical-session.target),
-- so systemd starts them itself once uwsm reaches that target -- restart-on-failure
-- included, and no risk of double-starting them from here too.
--
-- An earlier version of this file launched all four with hl.exec_cmd, copying
-- Omarchy's exec-once pattern. That was wrong on inspection: hyprpolkitagent's
-- binary isn't even on $PATH (it lives at /usr/lib/hyprpolkitagent/hyprpolkitagent),
-- so that line silently did nothing, and the other three worked by coincidence of
-- being on $PATH while duplicating what their own shipped services already do
-- properly. Enable the four services instead:
--   systemctl --user enable mako.service hypridle.service hyprpaper.service hyprpolkitagent.service
--
-- Phase 5 adds two more, both also shipped services (checked `pacman -Ql`/the
-- actual PKGBUILD for each, not assumed -- waybar was missed at first and only
-- caught because "waybar is running" failed in the live session):
--   systemctl --user enable waybar.service
--   systemctl --user enable cliphist.service   (runs `wl-paste --watch cliphist store`)

-- Phase 16: install/configure-base-system can't enable any of the above
-- itself -- systemctl --user needs a real session, which its install-time
-- chroot doesn't have. install/first-login does it here instead, gated by
-- its own marker file, so this is a genuine one-time action even though it
-- runs on every Hyprland start.
hl.exec_cmd("~/Projects/autarchy/install/first-login")
