#!/usr/bin/env bash
# ~/.config/hypr/hyprpaper.conf is generated now (D-0085): wallpaper-set writes it with
# the chosen image's real path, because hyprpaper 0.8.4 renders only what its config
# declares and ignores the runtime IPC we used before. A machine installed earlier has
# a stow link there, pointing into the payload, which stow would keep restoring over
# what wallpaper-set writes -- so replace it with a real file naming the current
# wallpaper. Idempotent: a real file (already generated) is left alone.
set -euo pipefail

config="$HOME/.config/hypr/hyprpaper.conf"
current="$HOME/.local/share/backgrounds/current.png"

[[ -L $config ]] || exit 0

target=$current
[[ -e $current ]] && target=$(realpath "$current")

rm -f "$config"
cat >"$config" <<CONF
# Generated by wallpaper-set (D-0085) -- edit the wallpaper, not this file:
#   wallpaper-set <path>    wallpaper-random [dir]    SUPER+CTRL+W
wallpaper {
  monitor = *
  path = $target
  fit_mode = cover
}

ipc = on
splash = false
CONF
