#!/usr/bin/env bats
# Unit tests for the migration that frees ~/.config/hypr/hyprpaper.conf to be a
# generated file (D-0085): until now it was a stow link into the payload, and stow
# would keep restoring it over what wallpaper-set writes.

setup() {
  load '../helpers/common'
  SCRIPT=$(ls "$REPO_ROOT"/migrations/*-hyprpaper-conf-generated.sh)
  export HOME="$BATS_TEST_TMPDIR/home"
  mkdir -p "$HOME/.config/hypr" "$HOME/.local/share/backgrounds"
  PAYLOAD="$BATS_TEST_TMPDIR/payload"
  mkdir -p "$PAYLOAD/home/hyprpaper/dot-config/hypr"
  : >"$PAYLOAD/home/hyprpaper/dot-config/hypr/hyprpaper.conf"
  : >"$HOME/.local/share/backgrounds/default.png"
  ln -sfn "$HOME/.local/share/backgrounds/default.png" "$HOME/.local/share/backgrounds/current.png"
}

@test "replaces the stow link with a real config naming the current wallpaper" {
  ln -s "$PAYLOAD/home/hyprpaper/dot-config/hypr/hyprpaper.conf" "$HOME/.config/hypr/hyprpaper.conf"
  run "$SCRIPT"
  assert_success
  assert [ ! -L "$HOME/.config/hypr/hyprpaper.conf" ]
  run cat "$HOME/.config/hypr/hyprpaper.conf"
  assert_output --partial "path = $HOME/.local/share/backgrounds/default.png"
}

@test "leaves a real config alone (already generated by wallpaper-set)" {
  echo "# generated, mine" >"$HOME/.config/hypr/hyprpaper.conf"
  run "$SCRIPT"
  assert_success
  run cat "$HOME/.config/hypr/hyprpaper.conf"
  assert_output "# generated, mine"
}

@test "is a no-op with nothing there, and on a second run" {
  run "$SCRIPT"
  assert_success
  run "$SCRIPT"
  assert_success
}
